#!/bin/bash

python_cmd="python3"

# Check if python3 is installed
if ! command -v $python_cmd &> /dev/null
then
    echo "Python3 could not be found"
    exit
fi

BASEDIR=$(dirname $0)
$python_cmd $BASEDIR/mfrc522.py $@
